name: Release

on:
  push:
    tags:
      - "v*"
  pull_request:
    types: [labeled, synchronize]

jobs:
  release:
    if: startsWith(github.ref, 'refs/tags/') || contains(github.event.pull_request.labels.*.name, 'test-release')
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v5
      - uses: jdx/mise-action@v3.4.0

      - name: Create release artifacts
        if: startsWith(github.ref, 'refs/tags/')
        run: mise run build-release --skip publish

      - name: Create release snapshot
        if: github.event_name == 'pull_request'
        run: mise run build-release --snapshot

      - name: Create release
        uses: softprops/action-gh-release@v2
        with:
          draft: ${{ github.event_name == 'pull_request' }}
          tag_name: ${{ github.event_name == 'pull_request' && github.event.pull_request.head.sha || github.ref_name }}
          files: |
            dist/*.tar.gz
            dist/*.zip
            dist/*_checksums.txt
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
